version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: titra

build:
  run_buildscript: false
  toolchains: []

images:
  - id: titra
    target: service
    service: titra_app
    source: docker.io/kromit/titra
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat

  - id: mongo
    target: service
    service: titra_db
    source: docker.io/library/mongo
    channel: stable
    sort: semver
    tag_regex: '^7\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    skip_if_version_exists: true
    create_if_missing: true
    changelog_locales: [zh, en]
    retry:
      enabled: false
      max_attempts: 3
      initial_delay: 2s
      max_delay: 30s
    application:
      language: zh
      name: titra
      source: https://github.com/lazycat-contrib/titra-lzcapp
      source_author: lazycat-contrib
  private:
    enabled: true
    skip_if_version_exists: true
    name: titra
    summary: titra for LazyCat
