application:
  subdomain: titra
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://titra_app:3000/
services:
  titra_app:
    # upstream: docker.io/kromit/titra:v1.0.10
    image: registry.lazycat.cloud/czyt/kromit/titra:5f3a8481cf3734f7
    environment:
      - ROOT_URL=https://${LAZYCAT_APP_DOMAIN}
      - MONGO_URL=mongodb://titra_db/titra?directConnection=true
      - PORT=3000
    depends_on:
      - titra_db
  titra_db:
    # upstream: docker.io/library/mongo:7.0.39
    image: registry.lazycat.cloud/czyt/library/mongo:11cdb2ee5b4aafa7
    environment:
      - MONGO_DB=titra
    binds:
      - /lzcapp/var/db:/data/db
    healthcheck:
      test:
        - CMD-SHELL
        - mongosh --eval  "db.adminCommand('ping')"
      start_period: 30s
