package: cloud.lazycat.app.titra
version: 1.0.12
name: titra
description: 面向自由职业者和小型团队的现代开源项目时间跟踪工具
homepage: https://github.com/kromitgmbh/titra
author: kromitgmbh
locales:
  en:
    name: titra
    description: Modern open-source project time tracking for freelancers and small teams.
  zh:
    name: titra
    description: 面向自由职业者和小型团队的现代开源项目时间跟踪工具。
